### PR TITLE
bottom tab

### PR DESCRIPTION
**Pull request by pkcwong**
- added bottom tab navigation
- configured onPress listeners
- added native-base dependency
- added vector-icons

### CODE REVIEW

**Comment by eric-yhy** [comment]
On Android version 4.4.4, there is no UI render warning. It is a kind of smart to render the screen without calling "this".

**Review by eric-yhy — DISMISSED** [review]
It is great to add tab bar.
As Ada is not working on your master, your version and her version will have conflicts when you merge her part. But, you can merge it to master if you want.

**Comment by pkcwong** [comment]
changed implementation to using TabNavigator, to avoid unecessary re-render of ui

**Comment by pkcwong** [comment]
fixed all routes, ready for merge

**Comment by pkcwong** [comment]
deprecated since RN 0.43.4

**Review by httpak — APPROVED** [review]

**Pull request merged**
